version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: frontend-basics-db
    environment:
      POSTGRES_DB: frontend_basics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  # Опционально: pgAdmin для управления базой данных
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: frontend-basics-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:

